### ISSUE TITLE
how to dismiss popup Viewcontroller with a Button.

### ISSUE THREAD

**Issue by jvashisht** [litt1e-p/UIViewController-PopUp#1]
I want to use this in my app but its crashing when i placed a button in popup viewcontroller to dismiss this controller. please reply ASAP. Thanks

**Comment by litt1e-p** [comment]
@jvashisht just call func `dismissPopUpViewController` or `dismissPopUpViewController(completion: (()->Void)?)`

**Comment by jvashisht** [comment]
i have already tried that, but its crashing and i think the reason is recentViewcontroller in your class, becoz now the recent viewcontroller is popup viewcontroller and i am calling this from the login controller if i dismiss from the login viewcontroller its working fine, but when i placed a button and try to dismiss from the popupviewcontroller its crashing. if you want i can share the code. thanks

**Comment by jvashisht** [comment]
Please reply ASAP, i am working on the same

**Comment by litt1e-p** [comment]
@jvashisht I think you should debug your project firstly, and show me the crash message

**Comment by jvashisht** [comment]
fatal error: unexpectedly found nil while unwrapping an Optional value
![screen shot 2017-10-30 at 5 40 50 pm](https://user-images.githubusercontent.com/26703845/32170159-8cdf9cb6-bd99-11e7-9d90-7589499e6081.png)

now the sourceview is popupView, i think thats,y its crashing

**Comment by litt1e-p** [comment]
@jvashisht what is your Xcode version and iOS version and Swift version?

**Comment by jvashisht** [comment]
Xcode version - 9
ios - 9.0
swift 4
i have updated your class.

**Comment by litt1e-p** [comment]
@jvashisht sorry, I dont have Mac now, please offer me a crash sample project if possible, and I will try to find out the crash reason later

**Comment by jvashisht** [comment]
Ok i will send you sample project & its good Library, Please update it to latest version.
Thanks.

**Comment by litt1e-p** [comment]
@jvashisht ok

**Comment by litt1e-p** [comment]
@jvashisht new swift 4 version was released

**Comment by litt1e-p** [comment]
@jvashisht the new version is released. please try it

**Comment by hassan-ml** [comment]
Hi, I've implemented a protocol to achieve the dismiss functionality on a button click.

1- Create a protocol in your 2nd View Controller
protocol VSCommentsDelegate: NSObjectProtocol {
    func dismissController()
}

2- Implement this protocol in your 1st View Controller from where you initiated the 2nd View Controller
extension VotesAndSurveyVC: VSCommentsDelegate {
    func dismissController() {
        dismissPopUpViewController()
    }
}

3- And dismiss here. It will work.

**Comment by hassan-ml** [comment]
You can also implement the protocol in this library I think that would be the best way. Because we might need to open these pop ups in many other controllers.

**Comment by litt1e-p** [comment]
@hassan-ml thanks a lot. I have implemented without protocol to achieve the same effect that can dismiss popup view inside it. please check its new pod and prepare [sample](https://github.com/litt1e-p/UIViewController-PopUp/tree/master/UIViewController-PopUp-Sample) project for reference

**Comment by litt1e-p** [comment]
@jvashisht thanks for your attension to this repo and it can dismiss the popup view inside it now. please take a look.

**Comment by hassan-ml** [comment]
Thanks, I have downloaded and installed and its working now. Thanks for this.

**Comment by litt1e-p** [comment]
@hassan-ml you are welcome
